---
apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-forklift
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: getpublickey-cert
  namespace: konveyor-forklift
spec:
  isCA: true
  dnsNames:
  - getpublickey.konveyor-forklift.svc
  - getpublickey.konveyor-forklift.svc.cluster.local
  commonName: getpublickey-cert
  secretName: getpublickey-serving-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: forklift-issuer
    kind: Issuer
    group: cert-manager.io