---
apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-forklift
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: getpublickey
  namespace: konveyor-forklift
  labels:
    app: getpublickey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getpublickey
  template:
    metadata:
      labels:
        app: getpublickey
    spec:
      volumes:
        - name: getpublickey-serving-cert
          secret:
            secretName: getpublickey-serving-cert
      containers:
        - name: getpublickey
          image: quay.io/kubev2v/getpublickey:latest
          volumeMounts:
            - name: getpublickey-serving-cert
              mountPath: /var/run/secrets/getpublickey-serving-cert
          ports:
            - containerPort: 8443
              protocol: TCP
          imagePullPolicy: Always
          command:
            - python
            - getpublickey.py
          args:
            - "--tls-key"
            - "/var/run/secrets/getpublickey-serving-cert/tls.key"
            - "--tls-crt"
            - "/var/run/secrets/getpublickey-serving-cert/tls.crt"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: getpublickey-serving-cert
  name: getpublickey
  namespace: konveyor-forklift
  labels:
    app: getpublickey
spec:
  ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: getpublickey
  type: ClusterIP
  sessionAffinity: None